apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: aura
  name: aiven-audit
  namespace: aura
spec:
  accessPolicy:
    outbound:
      external:
        - host: api.aiven.io
  image: {{ image }}
  liveness:
    failureThreshold: 3
    path: /nais/isalive
    periodSeconds: 10
    timeout: 1
  readiness:
    path: /nais/isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  skipCaBundle: true
  envFrom:
    - secret: aiven-audit
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: aiven-audit
  name: aiven-audit
  namespace: aura
type: Opaque
stringData:
  AIVEN_AUDIT_PAT: {{ aiven_audit_pat }}
