apiVersion: v1
kind: Secret
metadata:
  labels:
    app: aiven-audit
  name: aiven-audit
  namespace: aura
type: Opaque
stringData:
  AIVEN_AUDIT_PAT: "{{- .Values.app.secrets.aiven.pat | default "" }}"
