apiVersion: v2
name: aiven-audit
description: App that fetches project event logs from the Aiven API and logs them to standard out.
type: application
version: "0.0.2"
appVersion: "bogus"
sources:
  - "https://github.com/nais/aiven-audit/tree/main/charts/aiven-audit/"
