dependencies:
  - allOf:
      - naiserator
environmentKinds:
  - legacy
  - tenant
values:
  image.tag:
    description: Docker image tag
    config:
      type: string
  app.secrets.aiven.pat:
    displayName: Access token for the Aiven API
    computed:
      template: '"{{ .Env.aiven_application_token_aiven_audit }}"'
    config:
      type: string
      secret: true
