apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  {{- include "aiven-audit.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aiven-audit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aiven-audit.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          env:
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: "true"
            - name: PORT
              value: "8080"
            - name: TENANT
              value: "{{ .Values.tenant.name }}"
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1069
            runAsNonRoot: true
            runAsUser: 1069
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /tmp
              name: writable-tmp
      restartPolicy: Always
      securityContext:
        fsGroup: 1069
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ .Release.Name }}
      volumes:
        - emptyDir: { }
          name: writable-tmp
