apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "aiven-audit.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  egress:
    - to:
        - namespaceSelector: { }
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    - to:
        - ipBlock:
            cidr: {{ .Values.apiserverip }}/24
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nais-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
