apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "aiven-audit.selectorLabels" . | nindent 6 }}
  name: {{ .Release.Name }}
type: Opaque
stringData:
  AIVEN_AUDIT_PAT: "{{- .Values.app.secrets.aiven.pat | default "" }}"
