name: Build and deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

env:
  BUILDER_IMG: "cgr.dev/chainguard/go:1.20"
  RUNNER_IMG: "cgr.dev/chainguard/static"
  BASEIMG_ID: "https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main"
  BASEIMG_ISSUER: "https://token.actions.githubusercontent.com"

jobs:
  build_push_sign:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      id-token: write
    outputs:
      tag: "${{ steps.build_push_sign.outputs.tag }}"
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # ratchet:actions/checkout@v2
      - name: Install cosign
        uses: sigstore/cosign-installer@204a51a57a74d190b284a0ce69b44bc37201f343 # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.0.0'
      - name: Verify builder image
        run: cosign verify --certificate-identity ${{ env.BASEIMG_ID }} --certificate-oidc-issuer ${{ env.BASEIMG_ISSUER }} ${{ env.BUILDER_IMG }}
      - name: Verify runner image
        run: cosign verify --certificate-identity ${{ env.BASEIMG_ID }} --certificate-oidc-issuer ${{ env.BASEIMG_ISSUER }} ${{ env.RUNNER_IMG }}
      - uses: nais/platform-build-push-sign@8b336817c5749f179373fd63a7f511bae7246f10 # ratchet:nais/build-push-sign@main
        id: build_push_sign
        with:
          name: aiven-audit
          dockerfile: Dockerfile
          google_service_account: gh-aiven-audit
          push: true
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}

  deploy:
    name: Deploy to prod-gcp
    if: github.ref == 'refs/heads/main'
    needs: [build_push_sign]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # ratchet:actions/checkout@v2
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@e1d100f14637a6caa0aec40f5b5c7fd0c3ce500e # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          VAR: image=${{ needs.build_push_sign.outputs.tag }}
