name: Build and deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

env:
  RUNNER_IMG: "gcr.io/distroless/static-debian11:nonroot"
  BASEIMG_ID: "keyless@distroless.iam.gserviceaccount.com"
  BASEIMG_ISSUER: "https://accounts.google.com"

jobs:
  build_push_sign:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      id-token: write
    outputs:
      tag: "${{ steps.build_push_sign.outputs.tag }}"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v2
      - name: Install cosign
        uses: sigstore/cosign-installer@9614fae9e5c5eddabb09f90a270fcb487c9f7149 # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.2.1'
      - name: Verify runner image
        run: cosign verify --certificate-identity ${{ env.BASEIMG_ID }} --certificate-oidc-issuer ${{ env.BASEIMG_ISSUER }} ${{ env.RUNNER_IMG }}
      - uses: nais/platform-build-push-sign@main # ratchet:exclude
        id: build_push_sign
        with:
          name: aiven-audit
          dockerfile: Dockerfile
          google_service_account: gh-aiven-audit
          push: true
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}

  deploy:
    name: Deploy to prod-gcp
    if: github.ref == 'refs/heads/main'
    needs: [build_push_sign]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v2
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@0bca2c7e607d30fd757a2a23fb7d07b3ff96d540 # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml,.nais/alerts.yml
          VAR: image=${{ needs.build_push_sign.outputs.tag }},aiven_audit_pat=${{ secrets.AIVEN_AUDIT_PAT }}
