name: Go
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    paths:
      - '**.go'
      - .github/workflows/main.yml
      - '.nais/*'
      - Dockerfile
      - go.mod
      - go.sum
env:
  REGISTRY: europe-north1-docker.pkg.dev/nais-io/nais/images
  IMAGE_NAME: aiven-audit
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # ratchet:actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # ratchet:golangci/golangci-lint-action@v2
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # ratchet:actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # ratchet:actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: go test -v ./...
  docker:
    needs: [check, test]
    runs-on: ubuntu-20.04
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # ratchet:actions/checkout@v2
      - uses: nais/platform-build-push-sign@main # ratchet:nais/platform-build-push-sign@main
        id: build-push-sign
        with:
          name: aiven-audit
          google_service_account: gh-aiven-audit
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main' }}
    outputs:
      version: "${{ steps.build-push-sign.outputs.version }}"
  deploy:
    name: Deploy to prod-gcp
    if: github.ref == 'refs/heads/main'
    needs: [docker]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # ratchet:actions/checkout@v2
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@e1d100f14637a6caa0aec40f5b5c7fd0c3ce500e # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          VAR: image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.docker.outputs.version }},aiven_audit_pat=${{ secrets.AIVEN_AUDIT_PAT }}
